### ISSUE TITLE
[go-completer] Request failed: 0: getting file for Identifier: no PackageHandles

### ISSUE THREAD

**Issue by lonnywang** [ycm-core/ycmd#1442] opened 2020-06-06 08:07 UTC
**ycmd.completers.language_server.language_server_completer.ResponseFailedException: Request failed: 0: getting file for Identifier: no PackageHandles**

https://github.com/ycm-core/ycmd/issues/1442#issuecomment-640049089

**Comment by bstaletic** [comment] 2020-06-06 10:11
You'll have to provide more context. Turn on debug logging, reproduce the exception and repost the logs.

**Comment by puremourning** [comment] 2020-06-06 11:25
Please see YCM’s CONTRIBUTING.md for the sort of level of detail we require. In short we require a minimal reproducible test care and at least an explanation of the problem.

**Comment by lonnywang** [comment] 2020-06-06 12:03
```sh
$ tree test_project
test_project
└── src
    └── main
        └── main.go
```

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}
```

```sh
$ echo $GOPATH
/home/user/go:/home/user/workspace/test_project
```

```
2020-06-06 19:55:31,180 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
2020-06-06 19:55:31,247 - INFO - Received ready request
2020-06-06 19:55:31,251 - INFO - Received signature help available request
2020-06-06 19:55:31,253 - INFO - Received event notification
2020-06-06 19:55:31,253 - DEBUG - Event name: BufferVisit
2020-06-06 19:55:31,254 - INFO - Received event notification
2020-06-06 19:55:31,254 - DEBUG - Event name: FileReadyToParse
2020-06-06 19:55:31,254 - INFO - Adding buffer identifiers for file: /data/user/workspace/test_project/src/main/main.go
2020-06-06 19:55:31,255 - DEBUG - No Settings function defined in /home/user/.vim/plugged/YouCompleteMe/.ycm_extra_conf.py
2020-06-06 19:55:31,255 - INFO - Starting gopls: ['/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/go/bin/gopls', '-logfile', None, '-rpc.trace']
2020-06-06 19:55:31,260 - INFO - gopls started
2020-06-06 19:55:31,260 - DEBUG - TX: Sending message: b'Content-Length: 1001\r\n\r\n{"id":1,"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"documentationFormat":["plaintext","markdown"]},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"contentFormat":["plaintext","markdown"]},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext","markdown"],"parameterInformation":{"labelOffsetSupport":false}}},"synchronization":{"didSave":true}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynamicRegistration":true},"documentChanges":true}},"initializationOptions":{"fuzzyMatching":false,"hoverKind":"Structured"},"processId":30823,"rootPath":"/data/user/workspace/test_project","rootUri":"file:///data/user/workspace/test_project"}}'
2020-06-06 19:55:31,297 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":true,"foldingRangeProvider":true,"executeCommandProvider":{"commands":["tidy","upgrade.dependency","generate"]},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":""}},"id":1}'
2020-06-06 19:55:31,297 - INFO - Language server requires sync type of Incremental
2020-06-06 19:55:31,297 - DEBUG - go: Server declares trigger characters: ['.']
2020-06-06 19:55:31,298 - INFO - go: Using trigger characters for semantic triggers: .
2020-06-06 19:55:31,298 - DEBUG - go: Server declares signature trigger characters: ['(', ',']
2020-06-06 19:55:31,298 - INFO - go: Using characters for signature triggers: (,,
2020-06-06 19:55:31,298 - DEBUG - TX: Sending notification: b'Content-Length: 52\r\n\r\n{"jsonrpc":"2.0","method":"initialized","params":{}}'
2020-06-06 19:55:31,298 - DEBUG - TX: Sending notification: b'Content-Length: 132\r\n\r\n{"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"fuzzyMatching":false,"hoverKind":"Structured"}}}'
2020-06-06 19:55:31,298 - DEBUG - Refreshing file /data/user/workspace/test_project/src/main/main.go: State is Open/action Open
2020-06-06 19:55:31,300 - DEBUG - TX: Sending notification: b'Content-Length: 274\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"go","text":"package main\\n\\nimport \\"fmt\\"\\n\\nfunc main() {\\n\\tfmt.Println(\\"Hello, World!\\")\\n}\\n","uri":"file:///data/user/workspace/test_project/src/main/main.go","version":1}}}'
2020-06-06 19:55:31,300 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"workspace/didChangeWatchedFiles","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"**/*.go","kind":7}]}}]},"id":1}'
2020-06-06 19:55:31,301 - DEBUG - TX: Sending response: b'Content-Length: 38\r\n\r\n{"id":1,"jsonrpc":"2.0","result":null}'
2020-06-06 19:55:31,306 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 Build info\\n----------\\ngolang.org/x/tools/gopls 0.4.0\\n    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=\\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\\n    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\\n    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=\\n    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=\\n    golang.org/x/tools@v0.0.0-20200407041343-bf15fae40dea h1:DUwLyMDMUauGMd9kSLIlhhYJNELm06HuxeBdkFkeax4=\\n    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=\\n    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=\\n    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=\\n\\nGo info\\n-------\\ngo version go1.14.4 linux/amd64\\n\\n"}}'
2020-06-06 19:55:31,352 - INFO - Server reported: 2020/06/06 19:55:31 Build info
----------
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200407041343-bf15fae40dea h1:DUwLyMDMUauGMd9kSLIlhhYJNELm06HuxeBdkFkeax4=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
    mvdan.cc/xurls/v2@v2.1.0 h1:KaMb5GLhlcSX+e+qhbRJODnUUBvlw01jt4yrjFIHAuA=

Go info
-------
go version go1.14.4 linux/amd64


2020-06-06 19:55:31,357 - INFO - Received filetype completion available request
2020-06-06 19:55:31,376 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 go/packages.Load\\n\\tsnapshot=0\\n\\tdirectory=/data/user/workspace/test_project\\n\\tquery=[./ builtin]\\n\\tpackages=2"}}'
2020-06-06 19:55:31,376 - INFO - Server reported: 2020/06/06 19:55:31 go/packages.Load
	snapshot=0
	directory=/data/user/workspace/test_project
	query=[./ builtin]
	packages=2
2020-06-06 19:55:31,421 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 go env for /data/user/workspace/test_project\\n(valid build configuration = false)\\n(build flags: [])\\nGO111MODULE=\\"\\"\\nGOARCH=\\"amd64\\"\\nGOBIN=\\"\\"\\nGOCACHE=\\"/home/user/.cache/go-build\\"\\nGOENV=\\"/home/user/.config/go/env\\"\\nGOEXE=\\"\\"\\nGOFLAGS=\\"\\"\\nGOHOSTARCH=\\"amd64\\"\\nGOHOSTOS=\\"linux\\"\\nGOINSECURE=\\"\\"\\nGONOPROXY=\\"\\"\\nGONOSUMDB=\\"\\"\\nGOOS=\\"linux\\"\\nGOPATH=\\"/home/user/go:/home/user/workspace/test_project\\"\\nGOPRIVATE=\\"\\"\\nGOPROXY=\\"https://proxy.golang.org,direct\\"\\nGOROOT=\\"/usr/local/go\\"\\nGOSUMDB=\\"sum.golang.org\\"\\nGOTMPDIR=\\"\\"\\nGOTOOLDIR=\\"/usr/local/go/pkg/tool/linux_amd64\\"\\nGCCGO=\\"gccgo\\"\\nAR=\\"ar\\"\\nCC=\\"gcc\\"\\nCXX=\\"g++\\"\\nCGO_ENABLED=\\"1\\"\\nGOMOD=\\"\\"\\nCGO_CFLAGS=\\"-g -O2\\"\\nCGO_CPPFLAGS=\\"\\"\\nCGO_CXXFLAGS=\\"-g -O2\\"\\nCGO_FFLAGS=\\"-g -O2\\"\\nCGO_LDFLAGS=\\"-g -O2\\"\\nPKG_CONFIG=\\"pkg-config\\"\\nGOGCCFLAGS=\\"-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build314468838=/tmp/go-build -gno-record-gcc-switches\\"\\n"}}'
2020-06-06 19:55:31,421 - INFO - Server reported: 2020/06/06 19:55:31 go env for /data/user/workspace/test_project
(valid build configuration = false)
(build flags: [])
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go:/home/user/workspace/test_project"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build314468838=/tmp/go-build -gno-record-gcc-switches"

2020-06-06 19:55:31,428 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 go/packages.Load\\n\\tsnapshot=0\\n\\tdirectory=/data/user/workspace/test_project\\n\\tquery=[./]\\n\\tpackages=1"}}'
2020-06-06 19:55:31,428 - INFO - Server reported: 2020/06/06 19:55:31 go/packages.Load
	snapshot=0
	directory=/data/user/workspace/test_project
	query=[./]
	packages=1
2020-06-06 19:55:31,433 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 go/packages.Load\\n\\tsnapshot=0\\n\\tdirectory=/data/user/workspace/test_project\\n\\tquery=[./]\\n\\tpackages=1"}}'
2020-06-06 19:55:31,433 - INFO - Server reported: 2020/06/06 19:55:31 go/packages.Load
	snapshot=0
	directory=/data/user/workspace/test_project
	query=[./]
	packages=1
2020-06-06 19:55:31,438 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 go/packages.Load\\n\\tsnapshot=1\\n\\tdirectory=/data/user/workspace/test_project\\n\\tquery=[./]\\n\\tpackages=1"}}'
2020-06-06 19:55:31,439 - INFO - Server reported: 2020/06/06 19:55:31 go/packages.Load
	snapshot=1
	directory=/data/user/workspace/test_project
	query=[./]
	packages=1
2020-06-06 19:55:31,512 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 go/packages.Load\\n\\tsnapshot=1\\n\\tdirectory=/data/user/workspace/test_project\\n\\tquery=[file=/data/user/workspace/test_project/src/main/main.go]\\n\\tpackages=1"}}'
2020-06-06 19:55:31,512 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:31 go/packages.Load\\n\\tsnapshot=1\\n\\tpackage_path=\\"main\\"\\n\\tfiles=[/home/user/workspace/test_project/src/main/main.go]"}}'
2020-06-06 19:55:31,513 - INFO - Server reported: 2020/06/06 19:55:31 go/packages.Load
	snapshot=1
	directory=/data/user/workspace/test_project
	query=[file=/data/user/workspace/test_project/src/main/main.go]
	packages=1
2020-06-06 19:55:31,513 - INFO - Server reported: 2020/06/06 19:55:31 go/packages.Load
	snapshot=1
	package_path="main"
	files=[/home/user/workspace/test_project/src/main/main.go]
2020-06-06 19:55:37,539 - INFO - Received command request
2020-06-06 19:55:37,539 - INFO - Found executeCommandProvider support for command ExecuteCommand in go
2020-06-06 19:55:37,540 - INFO - Found codeActionProvider support for command FixIt in go
2020-06-06 19:55:37,540 - INFO - Found definitionProvider support for command GoToDefinition in go
2020-06-06 19:55:37,540 - INFO - Found definitionProvider support for command GoToDeclaration in go
2020-06-06 19:55:37,540 - INFO - Found definitionProvider support for command GoTo in go
2020-06-06 19:55:37,540 - INFO - Found typeDefinitionProvider support for command GoToType in go
2020-06-06 19:55:37,540 - INFO - Found implementationProvider support for command GoToImplementation in go
2020-06-06 19:55:37,540 - INFO - Found referencesProvider support for command GoToReferences in go
2020-06-06 19:55:37,540 - INFO - Found renameProvider support for command RefactorRename in go
2020-06-06 19:55:37,540 - INFO - Found documentFormattingProvider support for command Format in go
2020-06-06 19:55:37,540 - INFO - Always supporting StopServer for go
2020-06-06 19:55:37,540 - INFO - Always supporting RestartServer for go
2020-06-06 19:55:37,540 - INFO - Always supporting GetDoc for go
2020-06-06 19:55:37,540 - INFO - Always supporting GetType for go
2020-06-06 19:55:37,540 - DEBUG - Refreshing file /data/user/workspace/test_project/src/main/main.go: State is Open/action None
2020-06-06 19:55:37,541 - DEBUG - TX: Sending message: b'Content-Length: 194\r\n\r\n{"id":2,"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":5,"line":5},"textDocument":{"uri":"file:///data/user/workspace/test_project/src/main/main.go"}}}'
2020-06-06 19:55:37,618 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","error":{"code":0,"message":"getting file for Identifier: no PackageHandles","data":null},"id":2}'
2020-06-06 19:55:37,618 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:37 go/packages.Load\\n\\tsnapshot=1\\n\\tpackage_path=\\"main\\"\\n\\tfiles=[/home/user/workspace/test_project/src/main/main.go]"}}'
2020-06-06 19:55:37,619 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"2020/06/06 19:55:37 go/packages.Load\\n\\tsnapshot=1\\n\\tdirectory=/data/user/workspace/test_project\\n\\tquery=[file=/data/user/workspace/test_project/src/main/main.go]\\n\\tpackages=1"}}'
Traceback (most recent call last):
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/watchdog_plugin.py", line 97, in wrapper
    return callback( *args, **kwargs )
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 95, in RunCompleterCommand
    request_data ) )
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/completers/completer.py", line 414, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 58, in <lambda>
    lambda self, request_data, args: self.GoTo( request_data, [ 'Definition' ] )
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 2139, in GoTo
    result = self._GoToRequest( request_data, handlers[ 0 ] )
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 2120, in _GoToRequest
    REQUEST_TIMEOUT_COMMAND )[ 'result' ]
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 422, in GetResponse
    return response.AwaitResponse( timeout )
  File "/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 207, in AwaitResponse
    error.get( 'message' ) or 'No message' ) )
ycmd.completers.language_server.language_server_completer.ResponseFailedException: Request failed: 0: getting file for Identifier: no PackageHandles
2020-06-06 19:55:37,621 - INFO - Server reported: 2020/06/06 19:55:37 go/packages.Load
	snapshot=1
	package_path="main"
	files=[/home/user/workspace/test_project/src/main/main.go]
2020-06-06 19:55:37,621 - INFO - Server reported: 2020/06/06 19:55:37 go/packages.Load
	snapshot=1
	directory=/data/user/workspace/test_project
	query=[file=/data/user/workspace/test_project/src/main/main.go]
	packages=1
2020-06-06 19:55:43,834 - INFO - Received debug info request
2020-06-06 19:55:47,860 - DEBUG - in-event <InotifyEvent: src_path=b'/data/user/workspace/test_project/src/main/.main.go.swp', wd=3, mask=IN_MODIFY, cookie=0, name=.main.go.swp>
```

**Comment by bstaletic** [comment] 2020-06-06 12:16
I can't repro. Is there anything in the gopls log? What about `:YcmDebugInfo`? Do you have the go standard library?

**Comment by lonnywang** [comment] 2020-06-06 13:46
> I can't repro. Is there anything in the gopls log? What about `:YcmDebugInfo`? Do you have the go standard library?

* GOPATH have to contain the project path
* the source code main.go have to put in a folder like 'src/main/'
```
test_project
└── src
    └── main
        └── main.go
```

the :YcmDebugInfo
```
Printing YouCompleteMe debug information...
-- Completion API: 1
-- Client logfile: /tmp/ycm_7eryhboa.log
-- Server Python interpreter: /home/user/.local/bin/python3
-- Server Python version: 3.7.7
-- Server has Clang support compiled in: False
-- Clang version: None
-- Extra configuration file found and loaded
-- Extra configuration path: /home/user/.vim/plugged/YouCompleteMe/.ycm_extra_conf.py
-- Go completer debug information:
--   gopls running
--   gopls process ID: 26536
--   gopls executable: ['/data/user/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/go/bin/gopls', '-logfile', '/tmp/gopls_stderrgl_vyekp.log', '-rpc.trace']
--   gopls logfiles:
--     /tmp/gopls_stderrgl_vyekp.log
--   gopls Server State: Initialized
--   gopls Project Directory: /data/user/workspace/test_project/src/main
--   gopls Settings: {
--   "fuzzyMatching": false,
--   "hoverKind": "Structured"
-- }
-- Server running at: http://127.0.0.1:53191
-- Server process ID: 26494
-- Server logfiles:
--   /tmp/ycmd_53191_stdout_v17sj7z9.log
--   /tmp/ycmd_53191_stderr_vupcd3_7.log
```

**Comment by bstaletic** [comment] 2020-06-06 13:49
I've tried exactly that and I end up in `/usr/lib/go/src/fmt/print.go`. This is why I asked if you even have the standard library installed.

**Comment by lonnywang** [comment] 2020-06-06 13:53
> I've tried exactly that and I end up in `/usr/lib/go/src/fmt/print.go`. This is why I asked if you even have the standard library installed.

If I move the main.go to 'src/', or remove the project path from GOPATH, I end up with /usr/local/go/src/fmt/print.go too.

**Comment by lonnywang** [comment] 2020-06-06 14:00
There is a soft link cause the problem.
I link /data/user to /home/user.

To repro:
```sh
ln -s test_project link_project
export GOPATH=/path/to/link_project
```

**Comment by bstaletic** [comment] 2020-06-06 14:20
Now I can repro. Steps:

1. `mkdir -p project/src/main`
2. `ln -s project project_link`
3. `cd project # or cd project_link`
4. `echo -en 'package main\n\nimport "fmt"\n\nfunc main() {\n        fmt.Println("")\n}'`
5. `vim src/main/main.go`
6. `/Println<CR>:YcmCompleter GoTo`

This however doesn't look like a ycmd bug. Rather a gopls bug. Can you use go modules instead?

**Comment by lonnywang** [comment] 2020-06-06 14:34
> Now I can repro. Steps:
> 
> 1. `mkdir -p project/src/main`
> 2. `ln -s project project_link`
> 3. `cd project # or cd project_link`
> 4. `echo -en 'package main\n\nimport "fmt"\n\nfunc main() {\n        fmt.Println("")\n}'`
> 5. `vim src/main/main.go`
> 6. `/Println<CR>:YcmCompleter GoTo`
> 
> This however doesn't look like a ycmd bug. Rather a gopls bug. Can you use go modules instead?

Thanks.
I change my GOPATH to the real path rather than the link path, and it works.
By the way, how to use go modules instead?

And, gopls seems work fine?
```
$ gopls format main.go
package main

import "fmt"

func main() {
	fmt.Println("Hello, World!")
}
```

**Comment by bstaletic** [comment] 2020-06-06 14:59
You don't need `$GOPATH`. Instead, in a directory where you want the `main` package to be, just run `go mod init <project name>`.

Anyway, since this isn't a ycmd bug, I'm going to close it.

**Closed by bstaletic** 2020-06-06 14:59 UTC
