### ISSUE TITLE
Unable to use latest ycm versions for iOS development

### ISSUE THREAD

**Issue by rib** [ycm-core/ycmd#1240] opened 2019-04-28 14:22 UTC
So far I've been using `--system-libclang` to be able to work on projects that I cross-compile for iOS (namely: https://github.com/glimpse-project/glimpse), but as found in #1141, there are problems with using `--system-libclang` on macOS 10.14 (and in my case it doesn't work to instead use llvm installed via brew as suggested).

For example, with the latest ycm looking at the above Glimpse projected, then opening `src/glimpse_context.cc` in vim I currently see these diagnostics:
```
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd_check.h|105 col 14 error| 'arm_neon.h' file not found
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|107 col 29 error| unknown type name 'int32x4_t'; did you mean 'int32_t'? (FixIt available)
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|109 col 40 error| unknown type name 'int32x4_t'
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|115 col 25 error| unknown type name 'int32x4_t'
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|101 col 34 error| use of undeclared identifier 'x'
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|101 col 38 error| use of undeclared identifier 'vdupq_n_s32'
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|105 col 13 error| use of undeclared identifier 'x'
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|105 col 17 error| use of undeclared identifier 'vld1q_s32'
/Users/bob/src/glimpse/glimpse/subprojects/dlib/dlib/simd/simd4i.h|107 col 45 error| member initializer 'x' does not name a non-static data member or base class
```

(The project itself builds without errors via Meson + Ninja)

For now I'm using an older version of ycm but it would be good if I could update to newer versions, either by finding a fix/workaround for using `--system-libclang` or somehow supporting this use case via the downloaded, prebuilt llvm binaries. (Under #1141 I briefly mentioned a few things I looked / at tried, before reverting back to an older version of ycm)

Summary instructions for building Glimpse for iOS would be (more detail in project README.md):
```
pip3 install --user --upgrade git+https://github.com/glimpse-project/meson
sudo xcode-select -switch /Applications/Xcode.app
git clone https://github.com/glimpse-project/glimpse
mkdir glimpse/build-ios-debug
cd glimpse/build-ios-debug
meson --cross-file ../ios-xcode-arm64-cross-file.txt --buildtype=debug --default-library=static ..
ninja
```
That will also end up creating a `compile_commands.json` db under `build-ios-debug`

Here's a minimal snippit from compile_commands.json:
```
[
  {
    "directory": "/Users/bob/src/glimpse/glimpse/build-ios-debug",
    "command": "clang++ -Iglimpse_viewer@exe -I. -I.. -I../src -I../src/imgui -Isubprojects/dlib -I../subprojects/dlib -Isubprojects/glm-0.9.9-a2 -I../subprojects/glm-0.9.9-a2 -Isubprojects/libpng-1.6.17 -I../subprojects/libpng-1.6.17 -Isubprojects/pcl -I../subprojects/pcl -I../subprojects/pcl/common/include -Isubprojects/eigen-git-mirror-3.3.4 -I../subprojects/eigen-git-mirror-3.3.4 -Isubprojects/boost_1_69_0 -I../subprojects/boost_1_69_0 -I../subprojects/pcl/octree/include -I../subprojects/pcl/kdtree/include -I../subprojects/pcl/segmentation/include -I../subprojects/pcl/geometry/include -I../subprojects/flann/src/cpp -I../subprojects/pcl/search/include -I../subprojects/pcl/sample_consensus/include -I../subprojects/pcl/filters/include -I../subprojects/pcl/features/include -I../subprojects/pcl/2d/include -I../subprojects/pcl/ml/include -Isubprojects/libepoxy/include -I../subprojects/libepoxy/include -Isubprojects/libepoxy/src -I../subprojects/libepoxy/src -I../subprojects/glfm/include -Isubprojects/libepoxy/include/epoxy -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -miphoneos-version-min=11.4 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_THREAD_USE_LIB -DEIGEN_MPL2_ONLY -DDLIB_NO_GUI_SUPPORT -DDLIB_ENABLE_ASSERTS -DGLM_ENABLE_EXPERIMENTAL -DUSE_AVF -DUSE_GLFM '-DIMGUI_IMPL_OPENGL_LOADER_CUSTOM=<epoxy/gl.h>' -arch arm64 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -MD -MQ 'glimpse_viewer@exe/src_glimpse_viewer.cc.o' -MF 'glimpse_viewer@exe/src_glimpse_viewer.cc.o.d' -o 'glimpse_viewer@exe/src_glimpse_viewer.cc.o' -c ../src/glimpse_viewer.cc",
    "file": "../src/glimpse_viewer.cc"
  }
]
```

If I get a chance I'll see if I can perhaps make a reduced test case from this.

**Comment by rib** [comment] 2019-04-28 14:56
Okey, focusing on the missing `arm_neon.h` error above; one minimal reproduction based on the above `compile_commands.json` generated for Glimpse via Meson is:

`ycm-test/compile_commands.json`:
```
[
  {
    "directory": "/tmp/ycm-test",
    "command": "clang++ -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -miphoneos-version-min=11.4 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -arch arm64 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -MD -MQ 'test.cc.o' -MF 'test.cc.o.d' -o 'test.cc.o' -c test.cc",
    "file": "test.cc"
  }
]
```
(absolute "directory" for ycm-test directory may need changing locally)

`ycm-test/test.cc`
```
#include <arm_neon.h>

int
test_symbol(int a)
{
    return a;
}
```

Manually running `clang++ -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++14 -g -miphoneos-version-min=11.4 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -arch arm64 -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -MD -MQ 'test.cc.o' -MF 'test.cc.o.d' -o 'test.cc.o' -c test.cc` on the command line works, but opening test.cc in vim with ycm shows the missing header diagnostic.

(this assumes having the `iPhoneOS12.1.sdk` downloaded via Xcode, but could be tweaked for other versions of the SDK)

For reference the output `test.cc.o.d` shows the missing file is located under `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/arm_neon.h`:
```
test.cc.o: test.cc \
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/arm_neon.h \
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/stdint.h \
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config \
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include/stdint.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/stdint.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_int8_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_int16_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_int32_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_int64_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/_types/_uint8_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/_types/_uint16_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/_types/_uint32_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/_types/_uint64_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/cdefs.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_symbol_aliasing.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_posix_availability.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/machine/_types.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/arm/_types.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_pthread/_pthread_types.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_intptr_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/machine/types.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/arm/types.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_u_int8_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_u_int16_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_u_int32_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_u_int64_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sys/_types/_uintptr_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/_types/_intmax_t.h \
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/_types/_uintmax_t.h
```

**Comment by puremourning** [comment] 2019-04-28 18:28
Thanks for the reproduction case.

Please could you include the diagnostics requested in YCM's CONTRIBUTING.md, such as the YcmDebugInfo output?

**Comment by rib** [comment] 2019-04-29 12:00
Below is my DebugInfo output, ycm logs and `vim --version` output.

```
Printing YouCompleteMe debug information...
-- Client logfile: /var/folders/cz/3mxyvqj13v71s2gf0d8syxzr0000gn/T/ycm_r3iwopcs.log
-- Server Python interpreter: /usr/bin/python
-- Server Python version: 2.7.10
-- Server has Clang support compiled in: True
-- Clang version: clang version 8.0.0 (tags/RELEASE_800/final)
-- No extra configuration file found
-- C-family completer debug information:
--   Compilation database path: /Users/bob/src/ycm-test
--   Flags: [u'clang++', u'-x', u'c++', u'-pipe', u'-Wall', u'-Winvalid-pch', u'-Wnon-virtual-dtor', u'-std=c++14', u'-g', u'-miphoneos-version-min=11.4', u'-isysroot', u'/Applicati
ons/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk', u'-arch', u'arm64', u'-fembed-bitcode', u'-isysroot', u'/Applications/Xcode.app/Conten
ts/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk', u'-resource-dir=/Users/bob/etc-dev/vim/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/cla
ng/8.0.0', u'-isystem', u'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1', u'-isystem', u'/Applications/Xcode.app/Contents/Develop
er/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/c++/v1', u'-isystem', u'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/S
DKs/iPhoneOS12.1.sdk/usr/local/include', u'-isystem', u'/usr/local/include', u'-isystem', u'/Users/bob/etc-dev/vim/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clang/lib/cl
ang/8.0.0/include', u'-isystem', u'/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include', u'-isystem', u'/Applications/Xcode.app/Contents/Devel
oper/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include', u'-iframework', u'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDK
s/iPhoneOS12.1.sdk/System/Library/Frameworks', u'-iframework', u'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/Library/Frame
works', u'-fspell-checking']
--   Translation unit: /Users/bob/src/ycm-test/test.cc
-- Server running at: http://127.0.0.1:56664
-- Server process ID: 21559
-- Server logfiles:
--   /var/folders/cz/3mxyvqj13v71s2gf0d8syxzr0000gn/T/ycmd_56664_stdout_jj412jd1.log
--   /var/folders/cz/3mxyvqj13v71s2gf0d8syxzr0000gn/T/ycmd_56664_stderr_hgbyv5yw.log
```

log 1
```
2019-04-29 12:51:51,683 - ERROR - HTTPConnectionPool(host='127.0.0.1', port=56664): Max retries exceeded with url: /ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x112e71208>: Failed to establish a new connection: [Errno 61] Connection refused'))
2019-04-29 12:51:51,789 - ERROR - HTTPConnectionPool(host='127.0.0.1', port=56664): Max retries exceeded with url: /ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x112e71780>: Failed to establish a new connection: [Errno 61] Connection refused'))
2019-04-29 12:51:51,892 - ERROR - HTTPConnectionPool(host='127.0.0.1', port=56664): Max retries exceeded with url: /ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x112e71c88>: Failed to establish a new connection: [Errno 61] Connection refused'))
```
log 2
```
2019-04-29 12:51:52,035 - INFO - Received event notification
2019-04-29 12:51:52,035 - DEBUG - Event name: FileReadyToParse
2019-04-29 12:51:52,035 - INFO - Adding buffer identifiers for file: /Users/bob/src/ycm-test/test.cc
2019-04-29 12:51:52,110 - INFO - Received filetype completion available request
2019-04-29 12:52:18,252 - INFO - Received debug info request
2019-04-29 12:52:23,012 - INFO - Received debug info request
2019-04-29 12:52:25,389 - INFO - Received debug info request
```
log 3
```
serving on http://localhost:56664
```

`vim --version`
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 25 2018 15:46:00)
macOS version
Included patches: 1-280
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +timers
++builtin_terms    -gettext           +num64             +title
+byte_offset       -hangul_input      +odbeditor         +toolbar
+channel           +iconv             +packages          +transparency
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       -xpm
-ebcdic            +mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -L.  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -framework Ruby    
```

All running on macOS 10.14 (Mojave)

**Comment by puremourning** [comment] 2020-09-20 20:21
as this is referring to Mojave and there have been a lot of changes since then (e.g. in clangd). I'm gong to close this. If it's still an issue, please re-open.

**Closed by puremourning** 2020-09-20 20:21 UTC
