### ISSUE TITLE
Support running omnisharp server without a solution file

### ISSUE THREAD

**Issue by abingham** [ycm-core/ycmd#101] opened 2015-03-20 09:44 UTC
From what I can tell, when `ycmd` uses `omnisharp` it requires that a solution file (i.e. a `.sln` file) exists. The `ycmd` code seems to actively check for such a file, and it refuses to start the server if it can't find one.

However, according to the closing remarks in [omnisharp issue 66](https://github.com/OmniSharp/omnisharp-vim/issues/66), you can now start omnisharp by just passing a directory instead of a solution file. It would be nice if `ycmd` allowed me to use this feature.

FWIW, I need this because I work with C# primarily on OX S (because it hurts more.) This is probably not a really pressing use case for many users, and there are reasonable workarounds like creating .sln files with xamarin studio. Still, if this is simple enough to do, it would be a nice bit of polish for `ycmd`.

**Comment by Valloric** [comment] 2015-03-20 17:06
@mispencer and @metatheos have worked on the C# completer recently, so they'd know more about this than I.

>  I need this because I work with C# primarily on OX S (because it hurts more.)

Thanks for this, I needed a chuckle this morning. :D

**Comment by abingham** [comment] 2015-03-21 08:43
Cheap giggles are what github issues are all about!

**Comment by metatheos** [comment] 2015-04-07 19:26
> I work with C# primarily on OX S (because it hurts more.)

Oh at least when writing Unity-code on OS X it's not bad at all. Unfortunately for other ycm-users it made me care less about fixing Omnisharp not being shut down correctly on Windows (the brave adventurers setting it up successfully on Windows deserve something better).

The actual change on ycm side for this should be fairly manageable. Right now there is some point where solution detection gives up because it fails to find a solution file. Trying to launch omnisharp with a directory would be good as an additional layer of fallback in that case, as I'm not sure how well users can deal with the error otherwise. In theory just replacing a few lines in ```cs_completer.py``` by
```py
    if not path_to_solutionfile:
      path_to_solutionfile = os.getcwdu()
      self._logger.info(
          u'Autodetection of solution file failed, trying current working directory ({0}).'
              .format( path_to_solutionfile ) )
    else:
      self._logger.info( u'Loading solution file {0}'.format( path_to_solutionfile ) )
```
should do the trick (or we could make the decision in the actual detection part, both options sound sane to me). We would need to agree on what directory to pass, my first choice would be the current working directory. The directory with the source file triggering the startup sequence would be an alternative (and in most cases they probably are the same).

I'll also need to figure out what to watch out for when starting omnisharp with a directory. In my initial experiments it crashes with a ```NullReferenceException``` after loading the source files from my test directory.

**Comment by metatheos** [comment] 2015-04-13 19:49
Turns out updating omnisharp was all I had to do. Now to figure out what the expected behavior is.

Which cases do we want the fallback to trigger in? If no solution is found at all, or in all cases where we fail to pick a solution? Right now the difference would be the case where we find multiple solution files, but can't tell which one covers the opened source file. We could start omnisharp without loading either, or not start omnisharp at all, so the user isn't confused by semi-broken completion.

If we then decide to start omnisharp with a directory, which one should it be?

**Comment by Valloric** [comment] 2015-04-16 20:51
@metatheos @abingham Since I don't write much C# these days, I'll leave those decisions up to you guys. :)

**Comment by vincentwoo** [comment] 2016-04-08 01:01
@metatheos was there any progress on this? I'm trying to determine if a `sln` file is necessary for omnisharp completion on *nix.

**Comment by teonivalois** [comment] 2016-04-11 23:10
What about for aspnetcore or dotnetcore where there isn't any *.sln file? We only have the "global.json" as the solution file (which is not even necessary) and the "project.json" as the project file. Any ideas?

**Comment by mispencer** [comment] 2016-04-11 23:35
Those will need to use the omnisharp-rosyln rewrite anyway, as the legacy omnisharp has no support for those project types. I believe it has detection logic for those cases. When we move the C# completer to that, such logic may need to duplicated here, or we may change our logic to defer that choice to omnisharp-roslyn.

FYI: There is a pull request for changing to omnisharp-roslyn already (https://github.com/Valloric/ycmd/pull/213) - I am waiting for omnisharp-rosyln to be more stable before attempting to move such PR forward.

**Comment by teonivalois** [comment] 2016-04-12 00:31
I just submitted a PR (#457) for supporting such projects. It required a two lines change in solutiondetection.py. It is working beatifully on my local. :)

**Comment by teonivalois** [comment] 2016-04-12 00:37
Ah, and forgot to mention that this is required to be a change in ycmd because it needs to pass the project/solution path to omnisharp-roslyn so it can provide the expected data. Before my change it was just failing with the _"Autodetection of solution file failed."_ error.

**Comment by vheon** [comment] 2016-04-12 20:21
> because it needs to pass the project/solution path to omnisharp-roslyn

we don't use omnisharp-roslyn at the moment

**Comment by teonivalois** [comment] 2016-04-12 21:20
but by adding this it would start working...

**Comment by vheon** [comment] 2016-04-12 22:03
> but by adding this it would start working...

@teonivalois do you mean that **when** we will switch to the omnisharp-roslyn it would be a thing already taken care of? Then I would agree 👍  Look at #213 if you want to keep track of changes or if you have anything to say about it 😃

**Comment by troubas** [comment] 2017-08-17 11:16
Leaving this here as I haven't found a good workaround anywhere and the issue seems to persist.

An easy way to get OmniSharp running is to create an empty .sln file in the working directory.

**Comment by puremourning** [comment] 2019-07-13 07:49
Is this still an issue with the new c-sharp completer? I'm inclined to close it and request a new issue is raised if it is still an issue.

**Comment by dragly** [comment] 2019-08-20 13:04
Works fine for me. However, if multiple solution files are present that do not fit with the heuristics of `ycmd/completers/cs/solutiondetection.py`, the `Autodetection of solution file failed` error pops up. 

To fix the issue for anyone who experiences the same: I had to add a `.ycm_extra_conf.py` to the project root that sets the correct solution file:
```
def CSharpSolutionFile(file_path):
    return 'MyProject.sln'
```

This will set it to a specific solution file independent of the filename. You can write a more clever function if you want to :)

**Comment by bstaletic** [comment] 2019-08-20 17:22
Great! If it's working we can close this issue.

@dragly Thanks for testing.

**Closed by bstaletic** 2019-08-20 17:22 UTC
