### ISSUE TITLE
Update jedi to v0.14.1

### ISSUE THREAD

**Issue by verschmelzen** [ycm-core/ycmd#1293] opened 2019-07-25 11:13 UTC
[Jedi v0.13.3](https://github.com/davidhalter/jedi/tree/v0.13.3) does not support Python annotations correctly https://github.com/davidhalter/jedi/issues/1377

**Comment by bstaletic** [comment] 2019-07-25 12:10
I've already tried updating the jedi/parso/numpydoc submodules. Generally two regressions happen:

- Jedi is unable to parse latest numpydoc because of https://github.com/numpy/numpydoc/pull/205
  - Might be intentional and we just need to update our tests
- `GoToReferences` on something like `int` or `str` (a builtin class) returns a ton of noise since https://github.com/davidhalter/jedi/commit/9cbf20aa48295df46ce3cb67f9506375023bc2a9
  - Looks like a jedi regression
- Jedi now has a new submodule, so a `git submodule update --init --recursive` is necessary.
  - Not really a problem, but we should expect users to complain.

**Comment by davidhalter** [comment] 2019-08-01 00:13
@bstaletic What do you mean by a ton of noise?

**Comment by bstaletic** [comment] 2019-08-01 07:38
This tests starts to fail: https://github.com/ycm-core/ycmd/blob/master/ycmd/tests/python/subcommands_test.py#L347

The test essentially runs `jedi.Script( 'str', 1, 0, '' ).usages()` and jedi returns the following:

```
[<Definition full_name='__main__.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.object.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.type.str', description='str'>, <Definition full_name='builtins.int.str', description='str'>, <Definition full_name='builtins.int.str', description='str'>, <Definition full_name='builtins.int.str', description='str'>, <Definition full_name='builtins.float.str', description='str'>, <Definition full_name='builtins.float.str', description='str'>, <Definition full_name='builtins.float.str', description='str'>, <Definition full_name='builtins.complex.str', description='str'>, <Definition full_name='builtins.complex.str', description='str'>, <Definition full_name='builtins.unicode.str', description='str'>, <Definition full_name='builtins.unicode.str', description='str'>, <Definition full_name='builtins.unicode.str', description='str'>, <Definition full_name='builtins.unicode.str', description='str'>, <Definition full_name='builtins.str', description='class str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.str.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.bytes.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.bytearray.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.memoryview.str', description='str'>, <Definition full_name='builtins.memoryview.str', description='str'>, <Definition full_name='builtins.list.str', description='str'>, <Definition full_name='builtins.dict.str', description='str'>, <Definition full_name='builtins.set.str', description='str'>, <Definition full_name='builtins.frozenset.str', description='str'>, <Definition full_name='builtins.range.str', description='str'>, <Definition full_name='builtins.property.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins._Writer.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.str', description='str'>, <Definition full_name='builtins.buffer.str', description='str'>, <Definition full_name='builtins.buffer.str', description='str'>, <Definition full_name='builtins.buffer.str', description='str'>, <Definition full_name='builtins.buffer.str', description='str'>, <Definition full_name='builtins.OSError.str', description='str'>, <Definition full_name='builtins.EnvironmentError.str', description='str'>, <Definition full_name='builtins.EnvironmentError.str', description='str'>, <Definition full_name='builtins.ImportError.str', description='str'>, <Definition full_name='builtins.ImportError.str', description='str'>, <Definition full_name='builtins.SyntaxError.str', description='str'>, <Definition full_name='builtins.SyntaxError.str', description='str'>, <Definition full_name='builtins.SyntaxError.str', description='str'>, <Definition full_name='builtins.UnicodeDecodeError.str', description='str'>, <Definition full_name='builtins.UnicodeDecodeError.str', description='str'>, <Definition full_name='builtins.UnicodeDecodeError.str', description='str'>, <Definition full_name='builtins.UnicodeDecodeError.str', description='str'>, <Definition full_name='builtins.UnicodeEncodeError.str', description='str'>, <Definition full_name='builtins.UnicodeEncodeError.str', description='str'>, <Definition full_name='builtins.UnicodeEncodeError.str', description='str'>, <Definition full_name='builtins.UnicodeEncodeError.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>, <Definition full_name='builtins.file.str', description='str'>]
```

And when ycmd receives that and sends it to a client like YCM, the client receives a bunch of duplicated `Builtin str` and `Builtin class str` entries in (a client's equivalent of vim's) quickfix list, easily covering the whole screen. The one entry which actually has a position to point to gets "drowned" in the lot of repeated results.

Contrast that to the jedi version that ycmd currently depends on, whose output to the above is:

```
[<Definition class str>, <Definition str>]
```

Which, according to the subcommands test results in one `Builtin str` and a result that actually has a position to point to.

**Comment by davidhalter** [comment] 2019-08-01 11:48
While there might be a bug with `full_name`, it's definitely not a bug that you get usages for str now. With typeshed there are now a lot of usages for str in the typeshed library. So it kind of makes sense that there's a longer list now. One could 

However, just as a general rule: `usages()` is bad. It's really not working well and I personally almost never use it. It has been bad since the beginning and probably should have never even been part of the public API. So not updating IMO is not a good idea, because it really is a much better version.

**Comment by bstaletic** [comment] 2019-08-01 12:06
> While there might be a bug with full_name, it's definitely not a bug that you get usages for str now. With typeshed there are now a lot of usages for str in the typeshed library. So it kind of makes sense that there's a longer list now.

And that would be fine if all the items in the list had an associated line, column and file name. Currently ycmd is doing [this](https://github.com/ycm-core/ycmd/blob/master/ycmd/completers/python/python_completer.py#L248-L255), which results in "description only" GoTo responses like `{'description': 'Builtin str'}`

> However, just as a general rule: usages() is bad. It's really not working well and I personally almost never use it. It has been bad since the beginning and probably should have never even been part of the public API. So not updating IMO is not a good idea, because it really is a much better version.

We are aware of that, but we have supported `GoToReferences` through `usages()` for a long time. Just pulling it out would be a breaking change.

**Comment by davidhalter** [comment] 2019-08-01 12:25
The definitions all have a line/column/filename. The problem is your `definition.in_builtin_module()` check. Just check if a column is available and you're good.

**Comment by bstaletic** [comment] 2019-08-01 12:48
Thanks, that worked.

Any idea about the numpydoc issue? 

- Test file: https://github.com/ycm-core/ycmd/blob/master/ycmd/tests/python/testdata/numpy_docstring.py
- Test: https://github.com/ycm-core/ycmd/blob/master/ycmd/tests/python/get_completions_test.py#L392-L412

Or should I ask in the numpydoc repo issue tracker?

**Comment by davidhalter** [comment] 2019-08-01 15:34
I haven't really changed anything about that, so it might be a regression, but it might also be a numpydoc issue.

The problem is that numpydoc sometimes throws weird errors so I just catch `Exception` at some point to avoid errors. So the easiest way to test why it is failing is just removing that catch.

I felt like I had issues with the newer numpydoc, but I'm not really sure what it was, I also didn't follow it too much, because we have tests that catch this kind of stuff usually.

**Comment by bstaletic** [comment] 2019-09-25 16:24
#1302 was merged 8 days ago.

**Closed by bstaletic** 2019-09-25 16:24 UTC
