### ISSUE TITLE
C/C++: server command to get compilation flags for file

### ISSUE THREAD

**Issue by deb0ch** [ycm-core/ycmd#691] opened 2017-01-12 14:11 UTC
Is there a server command (or completer subcommand) to get the compilation flags used for completion in a given file ? If not, would it be possible / easy to implement ?

I'm trying to develop some new features for Emacs/Spacemacs for which I would need to know about the compilation flags.

Currently the only way for me to get them is to parse the debugging info sent by ycmd server on request, but that method is non-optimal, hacky and fragile since it is not using a well-defined API.

I saw https://github.com/Valloric/ycmd/pull/601 on the verge of being merged which might help, but I'm not sure it will be adapted to my use-case. Being a debugging feature, I don't know how reliable it would be to use it in a non-debugging feature, or if it would be considered 'hacky'.

For reference, the features I'm trying to implement are:
- show a warning in the mode-line if the file used for completion from the compilation database is not the same as the one being edited. This is useful as we use heuristics to find replacement files (especially for headers), and by definition these heuristics might fail and find an irrelevant file (like a c file for a c++ `.h` header, or a file from a different project with irrelevant flags).
This way the risk would be transparent to the user
- use Emacs' built-in feature [hide-ifdef](https://www.emacswiki.org/emacs/HideIfDef), to which we need to provide the currently defined preprocessor macros. This command might be used to infer them. More reliable ways might exist, for which I will shortly open a separated issue.
- such a command is likely to be useful for features I haven't thought of yet.

**Comment by vheon** [comment] 2017-01-12 21:18
Either #692 is a duplicate of this or this is a duplicate of #692. Anyhow I responded on #692 to the question but here seems even more obvious: is the user that provides the flags for a particular file though the `.ycm_extra_conf.py` where the user define a function called `FlagsForFile` that given a file path it returns the flags for that file so I'm not sure is ycmd responsibility to give them back when the user already know. 

PS I was sure that we merged #601 😕

**Comment by deb0ch** [comment] 2017-01-13 13:39
Indeed it is the user who writes the `.ycm_extra_conf.py`. Although it is `ycmd` which loads and uses it without passing by the the editor, so the editor is not aware of what flags the `FlagsForFile` returned.

In the current state of things, the editor would have to somehow call the `FlagsForFile` function on its side to know about the flags.

This poses several issues:
- I'm not sure if it is possible to call a single python function from Elisp. It might imply providing a separate python file containing a `main` and providing it a way of finding the `global_conf.py` or `ycm_extra_conf.py` (which would be dirty and hacky).
- Even if it was possible, the user script would need to be ran twice, once for the server and once for the client. This is not optimal, especially if the heuristics are long to execute (which will more than likely happen in some cases).
- It could hang the editor if not done in an async request. Apparently, not all editors support asynchronous commands (for instance, Vim >8).

It would be a *lot* simpler if ycmd just gave us something that it already knows in a simple request, instead of trying dirty hacks to use from the client a python script that is supposed to be called by `ycmd`.

The other issue about compilation flags is a different separate issue from that one with different problematics, I will reply from there.

**Comment by puremourning** [comment] 2017-01-21 13:30
https://github.com/Valloric/ycmd/pull/601

Pretty sure this change implements the requested feature. @micbou can you confirm?

**Comment by micbou** [comment] 2017-01-22 09:10
> Pretty sure this change implements the requested feature. @micbou can you confirm?

#601 doesn't improve much the situation since the list of flags is still returned as a string.

> show a warning in the mode-line if the file used for completion from the compilation database is not the same as the one being edited. This is useful as we use heuristics to find replacement files (especially for headers), and by definition these heuristics might fail and find an irrelevant file (like a c file for a c++ .h header, or a file from a different project with irrelevant flags).
This way the risk would be transparent to the user

I don't see how the compilation flags will help for that.

**Comment by deb0ch** [comment] 2017-01-23 10:59
> I don't see how the compilation flags will help for that.

Oh, maybe I forgot to mention, I want to display a "warning" of some sort whenever the currently edited file is not the file used in the command line used by `ycmd`. I don't see any better or more reliable place to look than the compilation flags.

This whole feature is for now just an ongoing reflection / experiment to improve auto-completion user experience in Spacemacs, because apparently some users are confused and can spend quite some time of debugging just because we got them the wrong flags, and at the same time these heuristic save a lot of trouble in most cases so it would be a shame not to use them.

If I get all the flags in a single string it shouldn't be much of a problem, parsing that should be pretty easy and inexpensive.

**Comment by puremourning** [comment] 2020-09-20 20:24
This won't always be possible if clangd is using a complication database, but as mentioned the debug info does include the flags in some cases where ycm knows them.

**Closed by puremourning** 2020-09-20 20:24 UTC
