### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/usr/lib/youcompleteme/third_party/ycmd/ycmd/default_settings.json'

### ISSUE THREAD

**Issue by StarsTesla** [ycm-core/ycmd#1337] opened 2019-10-09 08:43 UTC
I dont know why I have such a problem when I type any character in MacOs Catalina

**Comment by bstaletic** [comment] 2019-10-09 10:20
Well, what's in the `/usr/lib/youcompleteme/third_party/ycmd/` folder? My guess is that whatever you are doing isn't pulling in the ycmd submodule.

Since this is not a bug, but a user support question, I'm going to close this. User questions should be asked on [gitter](https://gitter.im/Valloric/YouCompleteMe).

**Closed by bstaletic** 2019-10-09 10:20 UTC
